{% set name = "lynx" %}
{% set version = "2.8.9.1" %}
{% set sha256 = "387f193d7792f9cfada14c60b0e5c0bff18f227d9257a39483e14fa1aaf79595" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: lynx2.8.8rel.2.tar.bz2
  url: http://invisible-mirror.net/archives/lynx/tarballs/lynx2.8.9rel.1.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 1003
  # needs curses.h, not avail on win
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - openssl
    - ncurses
    - zlib
    - bzip2
# needs libidn11 in conda-forge (also disabled in build.sh)
#    - libidn
  run:
    - openssl
    - ncurses
    - zlib
    - bzip2
#    - libidn

test:
  commands:
    - lynx -dump http://google.com
    - lynx -dump https://google.com

about:
  home: http://invisible-island.net/lynx/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'Text-based web browser'
  description: |
    Lynx is a fully-featured World Wide Web (WWW) client for users running
    cursor-addressable, character-cell display devices.
  doc_url: http://lynx.invisible-island.net/lynx_help/
  dev_url: http://lynx.invisible-island.net/lynx_help/lynx-dev.html

extra:
  recipe-maintainers:
    - epruesse
