{% set name = "lynx" %}
{% set version = "2.9.1" %}
{% set sha256 = "a6db9b22c20df435df3757925a505531ce9a514d134742e935d71aa5c41339c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://invisible-mirror.net/archives/lynx/tarballs/lynx{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  # needs curses.h, not avail on win
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
  host:
    - openssl
    - ncurses
    - zlib
    - bzip2
    - libidn2
  run:
    - openssl
    - ncurses
    - zlib
    - bzip2
    - libidn2

test:
  commands:
    - lynx -dump http://google.com
    - lynx -dump https://google.com

about:
  home: http://invisible-island.net/lynx/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: 'Text-based web browser'
  description: |
    Lynx is a fully-featured World Wide Web (WWW) client for users running
    cursor-addressable, character-cell display devices.
  doc_url: http://lynx.invisible-island.net/lynx_help/
  dev_url: http://lynx.invisible-island.net/lynx_help/lynx-dev.html

extra:
  recipe-maintainers:
    - epruesse
